# Web Scraping (Jobstreet)
## Done by: Yann
### Source: https://www.jobstreet.com.sg/data-analyst-jobs/in-Singapore?pg=1

##

### Import Libraries

In [12]:
import csv
import requests
from bs4 import BeautifulSoup

##

### Extract Raw HTML

In [2]:
# This is only for the first page of Jobstreet
url = 'https://www.jobstreet.com.sg/data-analyst-jobs/in-Singapore'
response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')

job_listings = soup.find_all('div', class_='z1s6m00 _1hbhsw67i _1hbhsw66e _1hbhsw69q _1hbhsw68m _1hbhsw6n _1hbhsw65a _1hbhsw6ga _1hbhsw6fy')

# Optional. I'm checking how many postings are there per page
len(job_listings)

##

### Scrape Information

In [14]:
data_rows = []

for job in job_listings:    

    # Get Title
    title = job.find('span', class_='z1s6m00').text.strip()

    # Get company name
    company = job.find('a', class_='_6xa4xb0 z1s6m00 z1s6m0f rqoqz4').text.strip()  

    # Get Salary info
    salary_element = job.find('span', class_='z1s6m00 _1hbhsw64y y44q7i0 y44q7i3 y44q7i21 y44q7ih')    
    if salary_element and salary_element.find_next_sibling('span', class_='z1s6m00 _1hbhsw64y y44q7i0 y44q7i3 y44q7i21 y44q7ih'):
        salary = salary_element.find_next_sibling('span', class_='z1s6m00 _1hbhsw64y y44q7i0 y44q7i3 y44q7i21 y44q7ih').text.strip()
    else:
        salary = 'No Salary Displayed'
      
    # Get description    
    selling_points = job.find('div', class_='z1s6m00 _1hbhsw6ba _1hbhsw64y')
    if selling_points:
        points = selling_points.find_all('span', class_='z1s6m00 _1hbhsw64y y44q7i0 y44q7i1 y44q7i21 _1d0g9qk4 y44q7i7')
        if points:
            selling_points_text = ', '.join(point.get_text() for point in points)
        else:
            selling_points_text = 'No selling points available'
    else:
        selling_points_text = 'No selling points available'


    # Get date posted
    exact_date = job.find('time', class_='z1s6m00 _1hbhsw64y')
    date_posted = exact_date['datetime'].split('T')[0] if exact_date else 'No Date Available'
    how_long_ago = job.find('span', class_='z1s6m00 _1hbhsw64y y44q7i0 y44q7i1 y44q7i22 y44q7ih').text.strip()

    data_rows.append([title, company, salary, selling_points_text, date_posted, how_long_ago])
   

    print(f"Title: {title}")
    print(f"Company: {company}")
    print(f"Salary: {salary}")
    print(f"Description:\n{selling_points_text}")
    print(f"Date Posted: {date_posted}")
    print(f"Days elapsed: {how_long_ago}")
    print("\n")


    with open('job_listings.csv', 'w', newline='', encoding='utf-8') as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(['Title', 'Company', 'Salary', 'Description', 'Date Posted', 'Days Elapsed'])
        writer.writerows(data_rows)

Title: Business Analyst
Company: Rockwell Automation Singapore
Salary: No Salary Displayed
Description:
No selling points available
Date Posted: 2023-05-16
Days elapsed: 5d ago


Title: Data Analyst
Company: TÜV SÜD PSB Pte Ltd
Salary: SGD 4.5K - 8,000 monthly
Description:
Be the first to evaluate and optimise new technologies, Deliver safe, secure & sustainable solutions, Be the expert our customer trust
Date Posted: 2023-05-12
Days elapsed: 8d ago


Title: Data Scientist (Partner Company)
Company: SGInnovate
Salary: SGD 5K - 7,000 monthly
Description:
No selling points available
Date Posted: 2023-05-17
Days elapsed: 4d ago


Title: Business Analyst
Company: Cargo Community Network Pte Ltd
Salary: SGD 4.1K - 6,240 monthly
Description:
Hybrid, AWS and Variable Bonus, Flexible Benefits, Positive learning environment
Date Posted: 2023-05-16
Days elapsed: 5d ago


Title: Healthcare Business Analyst
Company: DCH AURIGA SINGAPORE
Salary: No Salary Displayed
Description:
5 days work week, Competitive renumerations, Medical/Insurance coverage
Date Posted: 2023-05-17
Days elapsed: 4d ago


Title: Additive Manufacturing Planner and Data Engineer
Company: Hamilton Sundstrand Pacific Aerospace Pte Ltd
Salary: No Salary Displayed
Description:
No selling points available
Date Posted: 2023-05-19
Days elapsed: 1d ago


Title: Operations Analyst (STRONG EXCEL SKILLS)
Company: Henatenn Holdings Pte Ltd
Salary: SGD 2.6K - 2,800 monthly
Description:
5 days work week, Fast Paced Environment, Dynamic and Challenging Work
Date Posted: 2023-05-18
Days elapsed: 2d ago


Title: Data Analyst
Company: InfoCepts Pte. Ltd.
Salary: No Salary Displayed
Description:
No selling points available
Date Posted: 2023-05-19
Days elapsed: 1d ago


Title: [GOVT] Data Analyst, Pharmaceutical Science - JL
Company: BGC Group (Outsourcing)
Salary: SGD 2.7K - 3,000 monthly
Description:
No selling points available
Date Posted: 2023-05-19
Days elapsed: 2d ago


Title: Data Analyst / Data Scientist (Office of Data and Intelligence)
Company: National University of Singapore
Salary: No Salary Displayed
Description:
No selling points available
Date Posted: 2023-05-19
Days elapsed: 2d ago


Title: Supply Chain Data Analyst
Company: Becton Dickinson and Company (Korn Ferry)
Salary: SGD 4K - 5,000 monthly
Description:
No selling points available
Date Posted: 2023-05-19
Days elapsed: 2d ago


Title: Data Analyst, Sales Operation (Tableau, Technology)
Company: Triton AI Pte Ltd
Salary: No Salary Displayed
Description:
No selling points available
Date Posted: 2023-05-19
Days elapsed: 1d ago


Title: Livestream Business Data Analyst
Company: BYTEDANCE PTE. LTD.
Salary: No Salary Displayed
Description:
No selling points available
Date Posted: 2023-05-18
Days elapsed: 3d ago


Title: Clinical Data Analyst
Company: National Cancer Centre Singapore Pte Ltd
Salary: No Salary Displayed
Description:
No selling points available
Date Posted: 2023-05-17
Days elapsed: 3d ago


Title: Data Analytics Associate
Company: BDO LLP
Salary: No Salary Displayed
Description:
No selling points available
Date Posted: 2023-05-18
Days elapsed: 3d ago


Title: HR Generalist & Data Analyst - (R_232797)
Company: Marsh McLennan
Salary: No Salary Displayed
Description:
No selling points available
Date Posted: 2023-05-18
Days elapsed: 3d ago


Title: Data Scientist (statistics)
Company: ALLIED SEARCH PTE. LTD.
Salary: SGD 4.5K - 7,500 monthly
Description:
No selling points available
Date Posted: 2023-05-20
Days elapsed: 17h ago


Title: Claims Analyst
Company: AIA SINGAPORE PRIVATE LIMITED
Salary: No Salary Displayed
Description:
Competitive salary package, Excellent benefits
Date Posted: 2023-05-19
Days elapsed: 2d ago


Title: Data Analyst /Scientist (Tech MNC/ SQL/ UP TO12K)
Company: Adecco Personnel Pte Ltd.
Salary: SGD 9K - 12,000 monthly
Description:
No selling points available
Date Posted: 2023-05-16
Days elapsed: 4d ago


Title: Research Associate (Data Analyst) (CARE/RM) 1
Company: National University of Singapore
Salary: No Salary Displayed
Description:
No selling points available
Date Posted: 2023-05-16
Days elapsed: 4d ago


Title: Data Scientist / Analyst
Company: Optimum Solutions (S) Pte Ltd
Salary: No Salary Displayed
Description:
No selling points available
Date Posted: 2023-05-16
Days elapsed: 5d ago


Title: Snr/ Data Analyst [Marketing Department, MNC] #JWL
Company: RECRUIT EXPRESS PTE LTD
Salary: No Salary Displayed
Description:
No selling points available
Date Posted: 2023-05-16
Days elapsed: 4d ago


Title: Business Analyst
Company: FPT Asia Pacific Pte Ltd
Salary: SGD 5K - 9,000 monthly
Description:
Unlimited opportunity to grow, Competitive compensation, Fun working culture
Date Posted: 2023-05-18
Days elapsed: 3d ago


Title: Business Analyst (B2B Implementation I Training Provided)
Company: EA RECRUITMENT PTE LTD
Salary: SGD 3.8K - 4,500 monthly
Description:
No selling points available
Date Posted: 2023-05-21
Days elapsed: 4h ago


Title: Business Analyst
Company: Cornerstone Global Partners
Salary: SGD 4K - 7,000 monthly
Description:
No selling points available
Date Posted: 2023-05-19
Days elapsed: 2d ago


Title: Pricing Analyst
Company: ALLIED SEARCH PTE. LTD.
Salary: SGD 4K - 7,000 monthly
Description:
No selling points available
Date Posted: 2023-05-20
Days elapsed: 17h ago


Title: Business Data Analyst (DPBS)
Company: Canon Singapore Pte Ltd
Salary: No Salary Displayed
Description:
No selling points available
Date Posted: 2023-05-15
Days elapsed: 6d ago


Title: Service Data Analyst (Tech MNC/ Excel / Fresh Grad Welcome)
Company: Adecco Personnel Pte Ltd.
Salary: SGD 3K - 3,800 monthly
Description:
No selling points available
Date Posted: 2023-05-14
Days elapsed: 6d ago


Title: Research Analyst (Tanker)(Shipping MNC)
Company: GMP Technologies - Engineering
Salary: No Salary Displayed
Description:
No selling points available
Date Posted: 2023-05-21
Days elapsed: 2h ago


Title: Manager, Data Science and Analytics (S'porean, Python, Tableau, AWS/Azure, ETL)
Company: GMP Technologies - IT
Salary: SGD 5.5K - 6,000 monthly
Description:
No selling points available
Date Posted: 2023-05-18
Days elapsed: 3d ago